kind: Service
apiVersion: v1
metadata:
  name: myserver
  labels:
    app: myserver
spec:
  selector:
    app: myserver
  ports:
    - port: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myserver
  labels:
    app: myserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myserver
  template:
    metadata:
      labels:
        app: myserver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myserver"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: myserver
        image: localhost:5000/myserver:0.1
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myserver-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: myserver
          servicePort: 8080
