apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: graphdb
spec:
  type: bindings.azure.cosmosgraphdb
  version: v1
  metadata:
  - name: url
    value: 
  - name: masterKey
    value: 
  - name: username
    value: 
